### ISSUE TITLE
Bitcoin Wallet amount is off by a factor of 1000

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/cln-application#15]
The display value for the Bitcoin Wallet amount is off by a factor of 1000. That is, an actual on-chain balance of 100k sats shows up as 100M sats.

Originally posted by @shyfire131 in https://github.com/ElementsProject/cln-application/issues/6#issuecomment-1557705729

**Comment by ShahanaFarooqui** [comment]
Closing with PR #16.

**Comment by shyfire131** [comment]
Nice, Bitcoin wallet is fixed! And I am poorer again :(

Lightning transactions are empty now, probably due to some other changes in that Release branch around CLNWallet. Sorry if it's a WIP and this is a known issue :) 

![image](https://github.com/ElementsProject/cln-application/assets/116033104/2b0c6b84-7f47-47fc-9c38-af65b9b98a6f)

**Comment by ShahanaFarooqui** [comment]
> Lightning transactions are empty now, probably due to some other changes in that Release branch around CLNWallet. Sorry if it's a WIP and this is a known issue :)

It was due to the list stretching under the card. I just pushed an update to stop the stretch. Thanks for reporting.
